### ISSUE TITLE
How to use `IUserConsentVerifierInterop`

### ISSUE THREAD

**Issue by Hinton** [microsoft/windows-rs#1565]
### Which crate is this about?

windows

### Crate version

0.32.0

### Summary

Bit unsure if this is an actual bug or more of a usage error. I'm trying to use the `IUserConsentVerifierInterop` to prompt for Windows Hello. Since it provides support for define a window handler as `UserConsentVerifier.RequestVerificationAsync` has a tendency to appear behind other windows.

While running the code below I get an error suggesting the class cannot be loaded which leads me to suspect the correct DLL hasn't been loaded in the application. Is there a manual linking step which needs to be performed to get `WinRT` working?

Appreciate any assistance.

### Toolchain version/configuration
```
Default host: x86_64-pc-windows-msvc
rustup home:  C:\Users\Oscar\.rustup

installed toolchains
--------------------

stable-x86_64-pc-windows-msvc (default)
nightly-x86_64-pc-windows-msvc

active toolchain
----------------

stable-x86_64-pc-windows-msvc (default)
rustc 1.57.0 (f1edd0429 2021-11-29)
```

### Reproducible example

```rust
use windows::Security::Credentials::UI::*;
use windows::Win32::System::WinRT::IUserConsentVerifierInterop;
use windows::Win32::Foundation::HWND;
use windows::{core::*, Win32::System::Com::*};
use windows::Foundation::IAsyncOperation;

fn main() {
    unsafe { CoInitializeEx(std::ptr::null(), COINIT_MULTITHREADED).unwrap() };

    let message = HSTRING::from("hello world");
    let hw: HWND = HWND::default();

    let verifier: IUserConsentVerifierInterop = unsafe { CoCreateInstance(&IUserConsentVerifierInterop::IID, None, CLSCTX_ALL).unwrap() };
    let test: Result<IAsyncOperation<UserConsentVerificationResult>> = unsafe { verifier.RequestVerificationForWindowAsync(hw, message) };
}
```

### Crate manifest

```toml
[package]
name = "desktop_native"
version = "0.1.0"
license = "GPL-3.0"
edition = "2018"
exclude = ["index.node"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.17.0", features = ["full"] }

[target.'cfg(windows)'.dependencies.windows]
version = "0.32.0"
features = [
    "Foundation",
    "Security_Credentials_UI",
    "Win32_Foundation",
    "Win32_Security_Cryptography_UI",
    "Win32_System_Com",
    "Win32_System_WinRT"
]
```

### Actual behavior

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { code: 0x80040154, message: Class not registered
 }', src\main.rs:13:128

### Additional comments

Running the exe in Visual Studio provides the following additional error messages:

```
onecore\com\combase\objact\objact.cxx(4080)\combase.dll!00007FFD94C45105: (caller: 00007FFD94C41B12) ReturnHr(1) tid(dbf8) 80040154 Class not registered
onecore\com\combase\dcomrem\resolver.cxx(2209)\combase.dll!00007FFD94C42488: (caller: 00007FFD94C40D2E) ReturnHr(2) tid(dbf8) 80040154 Class not registered
onecore\com\combase\dcomrem\resolver.cxx(2412)\combase.dll!00007FFD94C40D56: (caller: 00007FFD94C41776) ReturnHr(3) tid(dbf8) 80040154 Class not registered
Exception thrown at 0x00007FFD9431478C in desktop_native.exe: Microsoft C++ exception:  ?? ::st_panic at memory location 0x00000091605EEF88.
```
