### ISSUE TITLE
Bug: CoRegisterClassObject should take flags as REGCLS, but it's actually a u32

### ISSUE THREAD

**Issue by zaddach** [microsoft/windows-rs#1589]
### Which crate is this about?

windows

### Crate version

0.33

### Reproducible example

```rust
use windows::Win32::System::Com::{
        IClassFactory, IClassFactory_Impl, CoRegisterClassObject, CLSCTX_LOCAL_SERVER, REGCLS_MULTI_SEPARATE,
};
use windows::core::{
    GUID,
    IUnknown,
    implement,
};

const SAMPLE_GUID: GUID = GUID::from_u128(0x00000000_0000_0000_0000_000000000000);


#[implement(IClassFactory)]
struct Factory;

impl IClassFactory_Impl for Factory {
    fn CreateInstance(&self,_punkouter: &core::option::Option<windows::core::IUnknown>,_riid: *const windows::core::GUID,_ppvobject: *mut*mut core::ffi::c_void) ->  windows::core::Result<()> {
                todo!()
    }


    fn LockServer(&self,_flock: windows::Win32::Foundation::BOOL) ->  windows::core::Result<()> {
        todo!()
    }
}

pub fn main() {
        unsafe {
                let unknown: IUnknown = Factory.into();
                let _ = CoRegisterClassObject(&SAMPLE_GUID, unknown, CLSCTX_LOCAL_SERVER, REGCLS_MULTI_SEPARATE.0 as u32).unwrap();
        }
}
```

### Crate manifest

```toml
[package]
name = "bug_report"
version = "0.1.0"
edition = "2021"

[dependencies.windows]
version = "0.33.0"
features = [
    "alloc",
    "Win32_Foundation",
    "implement",
    "Win32_System_Com",
]
```

### Expected behavior

I'd expect `CoRegisterClassObject` to accept the `REGCLS_MULTI_SEPARATE` flags parameter without casting.

### Actual behavior

Casting is needed because the parameter takes a `u32` instead of  `REGCLS`.
