### ISSUE TITLE
Bug: Incorrect value for `INVALID_SOCKET`

### ISSUE THREAD

**Issue by sunfishcode** [microsoft/windows-rs#1627]
### Which crate is this about?

windows-sys

### Crate version

0.34.0

### Summary

windows-sys appears to have an incorrect value for `INVALID_SOCKET`.

### Toolchain version/configuration

installed toolchains
--------------------

stable-x86_64-pc-windows-msvc (default)

installed targets for active toolchain
--------------------------------------

x86_64-pc-windows-msvc

active toolchain
----------------

stable-x86_64-pc-windows-msvc (default)
rustc 1.59.0 (9d1b2106e 2022-02-23)

### Reproducible example

```rust
fn main() {
    dbg!(winapi::um::winsock2::INVALID_SOCKET);
    dbg!(windows_sys::Win32::Networking::WinSock::INVALID_SOCKET);
}
```

### Crate manifest

```toml
[package]
name = "invalid"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winapi = { version = "0.3.9", features = ["winsock2"] }
windows-sys = { version = "0.34.0", features = ["Win32_Networking_WinSock"] }
```

### Expected behavior

[src\main.rs:2] winapi::um::winsock2::INVALID_SOCKET = 18446744073709551615
[src\main.rs:3] windows_sys::Win32::Networking::WinSock::INVALID_SOCKET = 18446744073709551615

### Actual behavior

[src\main.rs:2] winapi::um::winsock2::INVALID_SOCKET = 18446744073709551615
[src\main.rs:3] windows_sys::Win32::Networking::WinSock::INVALID_SOCKET = 4294967295
