### ISSUE TITLE
Bug: FindVolumeHandle::is_invalid() does not check for a value of -1

### ISSUE THREAD

**Issue by IanE9** [microsoft/windows-rs#1630]
### Which crate is this about?

windows

### Crate version

0.34.0

### Summary

``FindVolumeHandle::is_invalid()`` only considers the value ``0`` to represent an invalid handle which leads to incorrect branches being followed if a function returns a handle value of ``-1`` as its invalid handle code.

### Toolchain version/configuration

Default host: x86_64-pc-windows-msvc
rustup home:  C:\Users\Ian\.rustup

installed toolchains
--------------------

stable-x86_64-pc-windows-msvc
nightly-2022-01-27-x86_64-pc-windows-msvc
nightly-x86_64-pc-windows-msvc (default)

installed targets for active toolchain
--------------------------------------

i686-pc-windows-msvc
x86_64-pc-windows-msvc

active toolchain
----------------

nightly-x86_64-pc-windows-msvc (default)
rustc 1.61.0-nightly (d3ad51b48 2022-02-25)

### Reproducible example

```rust
use windows::Win32::Storage::FileSystem::{FindFirstVolumeW, FindVolumeClose};

fn main() {
    unsafe {
        // will return `-1` due to empty output buffer.
        let handle = FindFirstVolumeW(&mut []);
        if !handle.is_invalid() {
            // heap corruption due to handle being `-1`
            FindVolumeClose(handle);
        }
    }
}
```

### Crate manifest

```toml
[package]
name = "find_volume_bug"
version = "0.1.0"
edition = "2021"

[target.'cfg(windows)'.dependencies]
windows = { version = "0.34.0", features = ["Win32_Storage_FileSystem", "Win32_Foundation"] }
```

### Expected behavior

Body of ``if`` block is goes unentered because the handle is invalid and the program exits gracefully.

### Actual behavior

Body of ``if`` block is gets entered because the ``is_invalid`` fails to catch the value ``-1`` and the program exits due to heap corruption.
