### ISSUE TITLE
Feature request: turn on all features when generating docs

### ISSUE THREAD

**Issue by emilk** [microsoft/windows-rs#1681]
### Motivation

https://docs.rs/windows/latest/windows/ is very empty, lacking e.g. `SetFileTypes`. I believe this is simply because all feature are opt-in (which is great), but the docs are built with the default (empty) feature set.

This should be easily fixable by adding this to every `Cargo.toml`:

```toml
[package.metadata.docs.rs]
all-features = true
```

### Drawbacks

None
