### ISSUE TITLE
Bug: Access violation on `Interface` cast

### ISSUE THREAD

**Issue by Ben-Lichtman** [microsoft/windows-rs#1689]
### Which crate is this about?

windows

### Crate version

0.35.0

### Summary

I've been attempting to use the debug engine API through the windows crate, however I get an access violation when I try to create an `IDebugConctrol` out of my `IDebugClient`.

The following code should reproduce the crash:

### Toolchain version/configuration

rustc 1.62.0-nightly (306ba8357 2022-04-05)

### Reproducible example

```rust
use std::ptr::null_mut;
use windows::{
	core::Interface,
	Win32::System::Diagnostics::Debug::{DebugCreate, IDebugClient5, IDebugControl7},
};

fn main() {
	let mut client = null_mut();
	unsafe { DebugCreate(&IDebugClient5::IID, &mut client).unwrap() };
	let client = unsafe { &*client.cast::<IDebugClient5>() };

	let control = client.cast::<IDebugControl7>().unwrap();
}
```

### Crate manifest

```toml
[package]
name = "debug_engine"
version = "0.1.0"
edition = "2021"

[dependencies.windows]
version = "0.35.0"
features = [
    "Win32_System_Diagnostics_Debug",
]
```

### Expected behavior

the cast succeeds

### Actual behavior

access violation and crash
