### ISSUE TITLE
Bug: Missing traits in ROP_CODE struct

### ISSUE THREAD

**Issue by wawaron** [microsoft/windows-rs#1760]
### Which crate is this about?

windows

### Crate version

0.36.1

### Summary

The ROP_CODE struct cannot be used in the standard fashion when using multiple options.

### Toolchain version/configuration

Default host: x86_64-pc-windows-msvc
stable-x86_64-pc-windows-msvc (default)
rustc 1.60.0 (7737e0b5c 2022-04-04)

### Reproducible example

```rust
use windows::{Win32::Foundation::*, Win32::Graphics::Gdi::*, Win32::UI::WindowsAndMessaging::*};

fn main() {
    unsafe {
        let width: i32 = GetSystemMetrics(SM_CXSCREEN);
        let height: i32 = GetSystemMetrics(SM_CYSCREEN);
        let main_dc: HDC = GetDC(HWND(0));
        let buffer_dc: CreatedHDC = CreateCompatibleDC(main_dc);
        BitBlt(buffer_dc, 0, 0, width, height, main_dc, 0, 0, SRCCOPY|CAPTUREBLT);
    }
}
```

### Crate manifest

```toml
[dependencies]

[dependencies.windows]
version = "0.36.1"
features = [
    "Win32_Foundation",
    "Win32_Graphics_Gdi",
    "Win32_UI_WindowsAndMessaging"
]
```

### Expected behavior

Expected traits implemented like other structs of this type.
For example, the WINDOW_STYLE struct have traits implemented for BitAnd and BitOr operations.

### Actual behavior

Instead we have to do a bit more work with something like this ROP_CODE(SRCCOPY.0 | CAPTUREBLT.0).
