### ISSUE TITLE
MediaFoundation MFSetAttribute functions missing

### ISSUE THREAD

**Issue by TCROC** [microsoft/windows-rs#1766]
### Which crate is this about?

windows

### Crate version

0.36.1

### Summary

The MFSetAttributeRatio and MFSetAttribute size functions are missing

https://docs.microsoft.com/en-us/windows/win32/api/mfapi/nf-mfapi-mfsetattributesize

https://docs.microsoft.com/en-us/windows/win32/api/mfapi/nf-mfapi-mfsetattributeratio

![image](https://user-images.githubusercontent.com/24307049/169190518-7d989e5b-843d-478b-954f-22b072bca620.png)

### Crate manifest

```toml
[package]
name = "windwos_cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dependencies.windows]
version = "0.36.1"
features = [
    "Win32_Media_MediaFoundation"
]
```

### Additional comments

I'm currently working on converting this tutorial to Rust: https://docs.microsoft.com/en-us/windows/win32/medfound/tutorial--using-the-sink-writer-to-encode-video

I hit the MFSetAttributeRatio and MFSetAttributeSize functions and Rust-Analyzer didn't suggest me anything.  I did a shallow clone on the master branch to check and I can't find those 2 functions anywhere in the project.
