### ISSUE TITLE
`windows-sys` without CRT?

### ISSUE THREAD

**Issue by Zymlex** [microsoft/windows-rs#1989]
As I see, `windows-sys` uses `no_std`, but still try to link with CRT.
Is it possible to use `windows-sys` without CRT?

upd: https://github.com/microsoft/windows-rs/issues/1989#issuecomment-1230421401

**Comment by tim-weis** [comment]
Could you provide a repro?

I'm not sure I'm seeing the same as you are, however, the (failed) imports I see aren't *actually* from the CRT, but rather the SEH infrastructure (`__CxxFrameHandler3`, `_CxxThrowException`). I don't know where those are getting pulled in (or the `memset`s further down).

This is the repro I'm using:

*Cargo.toml*

```toml
[package]
name = "nostd_windows-sys"
version = "0.0.0"
edition = "2021"

[dependencies.windows-sys]
version = "0.36.1"
features = [
    "Win32_Foundation",
    "Win32_System_Threading",
]
```

*src/main.rs*

```rust
#![no_std]
#![no_main]

use core::panic::PanicInfo;

use windows_sys::Win32::System::Threading::{GetCurrentProcess, TerminateProcess};

#[panic_handler]
fn panic_abort(_info: &PanicInfo) -> ! {
    unsafe {
        let h = GetCurrentProcess();
        TerminateProcess(h, 1);
    };
    unreachable!();
}

#[no_mangle]
pub extern "C" fn EntryPoint() -> u32 {
    0
}
```

*.cargo/config.toml*

```toml
[build]
rustflags = [
    "-C", "link-arg=/ENTRY:EntryPoint"
]
```

(Note: I don't know why the linker cannot find the entry point.)
