### ISSUE TITLE
DLL issue with WaitOnAddress/WakeByAddressSingle/WakeByAddressAll

### ISSUE THREAD

**Issue by m-ou-se** [microsoft/windows-rs#2027]
### Which crate is this about?

windows-sys

### Crate version

0.36.1

### Summary

Using the WaitOnAddress/WakeByAddressSingle/WakeByAddressAll APIs works fine on Windows 10 pro, but results in 0xc0000142 (STATUS_DLL_INIT_FAILED) on GitHub's CI, which runs Windows Server 2022 (10.0.20348). The binary also fails to run in Wine, complaining that it can't find `vertdll.dll`.

`dumpbin /imports` shows that these three functions get imported from `vertdll.dll`, but I don't know whether that's correct, or whether that's also the problem I see on Windows Server.

### Toolchain version/configuration

Default config of GitHub's `windows-latest`:

```
 Default host: x86_64-pc-windows-msvc
rustup home:  C:\Users\runneradmin\.rustup

installed targets for active toolchain
--------------------------------------

i686-pc-windows-msvc
x86_64-pc-windows-msvc

active toolchain
----------------

stable-x86_64-pc-windows-msvc (default)
rustc 1.63.0 (4b91a6ea7 2022-08-08)
```

### Reproducible example

```rust
use windows_sys::Win32::System::Threading::WakeByAddressSingle;

fn main() {
    unsafe { WakeByAddressSingle(std::ptr::null()) };
}
```

### Crate manifest

```toml
[package]
name = "testcase"
version = "0.1.0"
edition = "2021"

[dependencies]
windows-sys = { version = "0.36", features = ["Win32_System_Threading", "Win32_Foundation"] }
```

### Expected behavior

Runs fine.

### Actual behavior

error: process didn't exit successfully: `target\debug\repro.exe` (exit code: 0xc0000142, STATUS_DLL_INIT_FAILED)
