### ISSUE TITLE
How to list available I2C Controllers and Devices?

### ISSUE THREAD

**Issue by felipebalbi** [microsoft/windows-rs#2038]
Hi,

I've been trying to understand how to use the I2C API to list all available I2C controllers in the system and, potentially, list all available I2C devices too by attempting to get a handle for each of valid addresses in each of the controllers. I have seen the existence of `GetControllersAsync()` within `windows::Devices::I2c::I2cController`, but that requires a provider of type `II2cProvider` which I can't understand how to create this argument.

Could someone provide an example showing how to properly use `GetControllersAsync()`?

Best regards

**Comment by kennykerr** [comment]
@jonwis do you know who can help with an API question?

**Comment by riverar** [comment]
The classes/interfaces you're working with are meant for I2C _providers_ looking to expose devices/controllers via Windows.Devices.I2c WinRT APIs. It sounds like you want to find devices connected to the system instead.

```rust
use windows::Devices::{Enumeration::DeviceInformation, I2c::I2cDevice};

fn main() -> windows::core::Result<()> {
    futures::executor::block_on(main_async())    
}

async fn main_async() -> windows::core::Result<()>
{
    let devices = DeviceInformation::FindAllAsyncAqsFilter(&I2cDevice::GetDeviceSelector()?)?.await?;
    
    let num_devices_found = devices.Size()?;
    println!("{num_devices_found} I2C devices found.");
    for i in 0..num_devices_found {
        let device = devices.GetAt(i)?;
        println!("[{i}] {}({})", device.Name()?, device.Id()?);
    }

    Ok(())
}
```

```toml
[package]
name = "app"
version = "0.0.0"
edition = "2018"
publish = false

[dependencies.windows]
version = "0.40.0"
features = [
    "Win32_Foundation",
    "Devices_Enumeration",
    "Devices_I2c",
    "Foundation_Collections",
]

[dependencies.futures]
version = "0.3"
```

If you need additional Windows API help, try posting on Microsoft Q&A at https://docs.microsoft.com/en-us/answers/topics/windows-api.html. There are engineers actively monitoring that.
