### ISSUE TITLE
Bug: LookupAccountNameW does not use Option for optional arguments

### ISSUE THREAD

**Issue by fgimian** [microsoft/windows-rs#2111]
### Which crate is this about?

windows

### Crate version

0.42.0

### Summary

As per the [docs](https://learn.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-lookupaccountnamew), this function has various optional arguments:

```c++
BOOL LookupAccountNameW(
  [in, optional]  LPCWSTR       lpSystemName,
  [in]            LPCWSTR       lpAccountName,
  [out, optional] PSID          Sid,
  [in, out]       LPDWORD       cbSid,
  [out, optional] LPWSTR        ReferencedDomainName,
  [in, out]       LPDWORD       cchReferencedDomainName,
  [out]           PSID_NAME_USE peUse
);
```

However, these are not marked as such in the Rust crate:

```rust
pub unsafe fn LookupAccountNameW<'a, P0, P1>(
    lpsystemname: P0,
    lpaccountname: P1,
    sid: super::Foundation::PSID,
    cbsid: *mut u32, referenceddomainname: ::windows::core::PWSTR,
    cchreferenceddomainname: *mut u32, peuse: *mut SID_NAME_USE) -> super::Foundation::BOOL
where
    P0: ::std::convert::Into<::windows::core::PCWSTR>,
    P1: ::std::convert::Into<::windows::core::PCWSTR>,
{
    #[cfg_attr(windows, link(name = "windows"))]
    extern "system" {
        fn LookupAccountNameW(lpsystemname: ::windows::core::PCWSTR, lpaccountname: ::windows::core::PCWSTR, sid: super::Foundation::PSID, cbsid: *mut u32, referenceddomainname: ::windows::core::PWSTR, cchreferenceddomainname: *mut u32, peuse: *mut SID_NAME_USE) -> super::Foundation::BOOL;
    }
    LookupAccountNameW(lpsystemname.into(), lpaccountname.into(), ::core::mem::transmute(sid), ::core::mem::transmute(cbsid), ::core::mem::transmute(referenceddomainname), ::core::mem::transmute(cchreferenceddomainname), ::core::mem::transmute(peuse))
}
```

Furthermore, PWSTR doesn't have a From implemntation from Option like PCWSTR so I'm left with something like this:

```rust
        let result = LookupAccountNameW(
            None, // Local Computer (this is technically a PCWSTR but is using the From trait defined)
            owner_name,
            PSID::default(),
            &mut owner_sid_size,
            PWSTR::null(),
            &mut domain_name_length,
            &mut sid_type,
        );
```

I would love to be able to call this function as follows instead (similar to various others):

```rust
        let result = LookupAccountNameW(
            None, // Local Computer
            owner_name,
            None,
            &mut owner_sid_size,
            None,
            &mut domain_name_length,
            &mut sid_type,
        );
```

### Toolchain version/configuration

```
Default host: x86_64-pc-windows-gnu
rustup home:  C:\Users\Fots\scoop\persist\rustup\.rustup

installed toolchains
--------------------

stable-x86_64-pc-windows-gnu (default)
stable-x86_64-pc-windows-msvc

active toolchain
----------------

stable-x86_64-pc-windows-gnu (default)
rustc 1.64.0 (a55dd71d5 2022-09-19)

```

### Reproducible example

```rust
N/A
```

### Crate manifest

```toml
[package]
name = "file-owners"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
widestring = "1.0.2"

[dependencies.windows]
version = "0.42.0"
features = [
    "Win32_Foundation",
    "Win32_Security",
    "Win32_Security_Authorization",
    "Win32_Storage_FileSystem",
    "Win32_System_Threading",
    "Win32_System_SystemServices",
]
```

### Expected behavior

lpSystemName, Sid and ReferencedDomainName should all be `Option<T>`s 😄 

### Actual behavior

Currently, all parameters are marked as required even though several of them are optional.

### Additional comments

I'm struggling to know where such issues originate (e.g. win32metadata vs windows-rs).  I searched win32metadata for the definition of this function and others that have optional arguments but couldn't see a distinction, so I'm guessing this is handled within windows-rs? 😄
