### ISSUE TITLE
Bug: Stack overflow when comparing BSTR with String

### ISSUE THREAD

**Issue by michaelwoerister** [microsoft/windows-rs#2115]
### Which crate is this about?

windows

### Crate version

0.42.0

### Summary

The program seems to end up in an infinite recursion for comparisons of the form `some_bstr == some_string`.

### Toolchain version/configuration

Default host: x86_64-pc-windows-msvc

installed toolchains
--------------------

(...)

installed targets for active toolchain
--------------------------------------

i686-pc-windows-msvc
x86_64-pc-windows-gnu
x86_64-pc-windows-msvc

active toolchain
----------------

stable-x86_64-pc-windows-msvc (default)
rustc 1.64.0 (a55dd71d5 2022-09-19)

### Reproducible example

```rust
use windows::core::BSTR;

fn main() {
    let bstr = BSTR::from("abc");
    let string = "abc".to_string();

    if bstr == string {
        println!("Hello World!");
    }
}
```

### Crate manifest

```toml
[package]
name = "bstr_hang_repro"
version = "0.1.0"
edition = "2021"

[dependencies.windows]
version = "0.42.0"
features = ["Win32_Foundation"]
```

### Expected behavior

No stack overflow `;)`

### Actual behavior

`thread 'main' has overflowed its stack`
