### ISSUE TITLE
Bug: Missmatch type in sample

### ISSUE THREAD

**Issue by paulober** [microsoft/windows-rs#2186]
### Which crate is this about?

windows

### Crate version

0.43.0

### Summary

The sample "message_box" does not compile on my fresh rust installation on Windows 11 22H2. It works if i change to code to this:
```rust
ShellMessageBoxW(None, None, w!("Wide"), w!("World"), MB_ICONERROR.0);
```

### Toolchain version/configuration

Default host: x86_64-pc-windows-msvc
rustup home: ~\.rustup

installed toolchains
--------------------

stable-x86_64-pc-windows-msvc

installed targets for active toolchain
-------------------------------------

x86_64-pc-windows-msvc
thumbv6m-none-eabi
x86_64-unknown-linux-gnu

active toolchain
----------------

stable-x86_64-pc-windows-msvc (default)
rustc 1.65.0 (897e37553 2022-11-02)

### Reproducible example

```rust
use windows::{core::*, Win32::UI::Shell::*, Win32::UI::WindowsAndMessaging::*};

fn main() {
    unsafe {
        ShellMessageBoxW(None, None, w!("Wide"), w!("World"), MB_ICONERROR);
    }
}
```

### Crate manifest

```toml
# ...

[dependencies.windows]
version = "0.43.0"
features = [
    "Win32_Foundation",
    "Win32_UI_WindowsAndMessaging",
    "Win32_UI_Shell",
]
```

### Expected behavior

It works like the example should.

### Actual behavior

It does not compile with following error: `expected 'u32', found struct 'MESSAGEBOX_STYLE'` ... `arguments to this function are incorrect`
