### ISSUE TITLE
Bug: If a GUI program has a space in its program exe file path, it'll failed started from windows service.

### ISSUE THREAD

**Issue by fengbenming** [microsoft/windows-rs#2205]
### Which crate is this about?

windows

### Crate version

0.43.0

### Summary

when I use CreateProcessAsUserW to start a GUI program from windows service,  if the the GUI program file path has space in it, it will started and then quit immediately. if the program file path has no space, it will started OK.

additional:  if start the GUI program not from windows service,  it'll ok in spite of a space in file path or not.

### Toolchain version/configuration

Default host: x86_64-pc-windows-msvc
rustup home:  C:\Users\PC\.rustup

stable-x86_64-pc-windows-msvc (default)
rustc 1.64.0 (a55dd71d5 2022-09-19)

### Reproducible example

```rust
pub unsafe fn get_cur_user_token() -> ::windows::core::Result<HANDLE> {
    let mut h_token: HANDLE = HANDLE::default();

    let snapshot_result = CreateToolhelp32Snapshot(TH32CS_SNAPPROCESS, 0);

    let snapshot = snapshot_result?;
    let mut process_entry = PROCESSENTRY32W {
        dwSize: std::mem::size_of::<PROCESSENTRY32W>() as u32,
        ..Default::default()
    };

    let cur_session_id = WTSGetActiveConsoleSessionId();

    if Process32FirstW(snapshot, &mut process_entry).as_bool() {
        loop {
            if Process32NextW(snapshot, &mut process_entry).as_bool() {
                let abc =
                    &process_entry.szExeFile[..PCWSTR::from(h!("explorer.exe")).as_wide().len()];
                if abc.eq(PCWSTR::from(h!("explorer.exe")).as_wide()) {
                    let mut psessionid: u32 = 0;
                    ProcessIdToSessionId(process_entry.th32ProcessID, &mut psessionid);
                    if cur_session_id != psessionid {
                        continue;
                    }

                    let handle_result = OpenProcess(
                        PROCESS_QUERY_INFORMATION,
                        false,
                        process_entry.th32ProcessID,
                    );

                    if OpenProcessToken(handle_result?, TOKEN_ALL_ACCESS, &mut h_token).as_bool() {
                        return Ok(h_token);
                    }

                    break;
                }
            } else {
                break;
            }
        }
    }
    Err(::windows::core::Error::new(HRESULT(1), HSTRING::new()))
}

pub fn create_process_as_user() -> AgentResult<()> {
    unsafe {
        let mut pi = PROCESS_INFORMATION::default();

        let si = STARTUPINFOW {
            cb: std::mem::size_of::<STARTUPINFOW>() as u32,
            dwFlags: STARTF_USESHOWWINDOW,
            wShowWindow: SW_SHOWMAXIMIZED.0 as u16,
            ..Default::default()
        };

        let package_exe = PCWSTR::from(h!(
            r#"C:\Users\PC\AppData\Local\xxxxx\xxxxx.exe"# // r"C:\Program Files\xxxxx\xxxxx.exe"
        ));

        let h_token: HANDLE = get_cur_user_token()?;

        let mut h_token_dup: HANDLE = HANDLE::default();

        if !DuplicateTokenEx(
            h_token,
            TOKEN_ALL_ACCESS,
            None,
            SecurityIdentification,
            TokenPrimary,
            &mut h_token_dup,
        )
        .as_bool()
        {
            CloseHandle(h_token);
            return Ok(());
        }

        if !CreateProcessAsUserW(
            h_token_dup,
            package_exe,
            PWSTR::null(),
            None,
            None,
            false,
            NORMAL_PRIORITY_CLASS.0 | CREATE_NEW_CONSOLE.0,
            None,
            None,
            &si,
            &mut pi,
        )
        .as_bool()
        {
            CloseHandle(h_token_dup);
        }
        Ok(())
    }
}
```

### Crate manifest

```toml
[dependencies]
windows-service = "0.5.0"
serde = { version = "1.0", features = ["derive"] }
reqwest = { version = "0.11", features = ["json"] }
tokio = { version = "1", features = ["full"] }
rust-crypto = "0.2.36"
dotenv = "0.15.0"
lazy_static = "1.4.0"

[dependencies.windows]
version = "0.43.0"
features = [
    "Win32_System_ApplicationInstallationAndServicing",
    "Win32_System_Threading",
    "Win32_Foundation",
    "Win32_Security",
    "Win32_UI_WindowsAndMessaging",
    "Win32_System_RemoteDesktop",
    "Win32_System_Diagnostics_ToolHelp",
    "Win32_System_EventLog",
    "Win32_System_Environment",
    "Win32_System_Registry",
]
```
