### ISSUE TITLE
Bug:

### ISSUE THREAD

**Issue by dtrebilco** [microsoft/windows-rs#2379]
### Which crate is this about?

windows-sys

### Crate version

0.45.0

### Summary

Using Wide string versions of the functions (eg CreateWindowExW ) do not seem to read the wide strings correctly. 
I suspect something along the way is treating it as UTF8 as only the first character is used. 
As the upper part of most u16 values is 0, this acts as the null terminator.

### Toolchain version/configuration

Default host: x86_64-pc-windows-msvc
rustup home:  C:\Rust\rustup

installed toolchains
--------------------

stable-x86_64-pc-windows-msvc (default)
nightly-2021-09-29-x86_64-pc-windows-msvc

installed targets for active toolchain
--------------------------------------

wasm32-unknown-unknown
x86_64-pc-windows-msvc

active toolchain
----------------

stable-x86_64-pc-windows-msvc (default)
rustc 1.65.0 (897e37553 2022-11-02)

### Reproducible example

```rust
// Modified version of the sample to use CreateWindowExW
use windows_sys::{
    core::*, Win32::Foundation::*, Win32::Graphics::Gdi::ValidateRect,
    Win32::System::LibraryLoader::GetModuleHandleA, Win32::UI::WindowsAndMessaging::*,
};

fn main() {
    unsafe {
        let instance = GetModuleHandleA(std::ptr::null());
        debug_assert!(instance != 0);

        let window_class = w!("window");

        let wc = WNDCLASSW {
            hCursor: LoadCursorW(0, IDC_ARROW),
            hInstance: instance,
            lpszClassName: window_class,
            style: CS_HREDRAW | CS_VREDRAW,
            lpfnWndProc: Some(wndproc),
            cbClsExtra: 0,
            cbWndExtra: 0,
            hIcon: 0,
            hbrBackground: 0,
            lpszMenuName: std::ptr::null(),
        };

        let atom = RegisterClassW(&wc);
        debug_assert!(atom != 0);

        CreateWindowExW(
            0,
            window_class,
            w!("This is a sample window"),
            WS_OVERLAPPEDWINDOW | WS_VISIBLE,
            CW_USEDEFAULT,
            CW_USEDEFAULT,
            CW_USEDEFAULT,
            CW_USEDEFAULT,
            0,
            0,
            instance,
            std::ptr::null(),
        );

        let mut message = std::mem::zeroed();

        while GetMessageA(&mut message, 0, 0, 0) != 0 {
            DispatchMessageA(&message);
        }
    }
}

extern "system" fn wndproc(window: HWND, message: u32, wparam: WPARAM, lparam: LPARAM) -> LRESULT {
    unsafe {
        match message {
            WM_PAINT => {
                println!("WM_PAINT");
                ValidateRect(window, std::ptr::null());
                0
            }
            WM_DESTROY => {
                println!("WM_DESTROY");
                PostQuitMessage(0);
                0
            }
            _ => DefWindowProcA(window, message, wparam, lparam),
        }
    }
}
```

### Crate manifest

```toml
[package]
name = "wintest"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dependencies.windows-sys]
version = "0.45.0"
features = [
    "Win32_Foundation",
    "Win32_System_LibraryLoader",
    "Win32_System_Performance",
    "Win32_UI",
    "Win32_UI_WindowsAndMessaging",
    "Win32_Graphics",
    "Win32_Graphics_Gdi",
    "Win32_Graphics_OpenGL",
]
```

### Expected behavior

The window title bar displays the correct name

### Actual behavior

Only the first character is displayed in the title name
![image](https://user-images.githubusercontent.com/7506147/224576728-794591ad-8c91-4f15-b3a6-eb708ea337ee.png)

### Additional comments

I played around also with SetWindowTextW after window creation and that did not seem to help.

Perhaps I am misunderstanding how these method should be used - as in utf8 is already somehow handled and passed through?
Or perhaps the app/os/Rust has some setting to treat all strings as utf8?
