### ISSUE TITLE
Bug: RegSetValueExW &[u8] encoding issue

### ISSUE THREAD

**Issue by FelixKLG** [microsoft/windows-rs#2389]
### Which crate is this about?

windows

### Crate version

0.44.0

### Summary

lpData requires &[u8], which causes encoding issues when inserting into the registry.

**Input:**
`"C:\Program Files\MyProgram\Program.exe"`

**Output:**
![image](https://user-images.githubusercontent.com/44820580/226218803-867c4156-b0e5-4042-929f-d9a0acabc11f.png)
`㩃停潲牧浡䘠汩獥䵜偹潲牧浡停潲牧浡攮數`

### Toolchain version/configuration

Default host: x86_64-pc-windows-msvc
rustup home:  C:\Users\felix\.rustup

installed toolchains
--------------------

stable-x86_64-pc-windows-msvc (default)
nightly-x86_64-pc-windows-msvc

active toolchain
----------------

stable-x86_64-pc-windows-msvc (default)
rustc 1.67.1 (d5a82bbd2 2023-02-07)

### Reproducible example

```rust
use windows::s;
use windows::w;

use windows::Win32::System::Registry::{
    RegCloseKey, RegCreateKeyExW, RegSetValueExW, HKEY, HKEY_LOCAL_MACHINE, KEY_ALL_ACCESS,
    REG_EXPAND_SZ, REG_OPTION_NON_VOLATILE,
};

fn main() {
    let reg_path = w!(r#"Software\Microsoft\Windows\CurrentVersion\Run"#);
    let key_name = w!("WinAPI Testing");
    let key_value = s!(r#"C:\Program Files\MyProgram\Program.exe"#);

    let mut hkey_target: HKEY = HKEY::default();

    unsafe {
        RegCreateKeyExW(
            HKEY_LOCAL_MACHINE,
            reg_path,
            0,
            None,
            REG_OPTION_NON_VOLATILE,
            KEY_ALL_ACCESS,
            None,
            &mut hkey_target,
            None,
        );

        let a = RegSetValueExW(
            hkey_target,
            key_name,
            0,
            REG_EXPAND_SZ,
            Some(key_value.as_bytes()),
        );
        // println!("{:?}", a);

        RegCloseKey(hkey_target);
    }
}
```

### Crate manifest

```toml
[package]
name = "winapi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.windows]
version = "0.44.0"
features = [
    "Win32_Foundation",
    "Win32_Security",
    "Win32_System_Registry"
    ]
```

### Expected behavior

Registry to have contents of `key_value`.

### Actual behavior

The registry has erroneous Unicode chars.

### Additional comments

I'm not sure if I'm doing anything wrong 😅
