### ISSUE TITLE
Bug: USBDevice::FromIdAsync

### ISSUE THREAD

**Issue by geahuam** [microsoft/windows-rs#2552]
### Which crate is this about?

windows

### Crate version

0.48.0

### Summary

Trying to get a USBDevice by ID results in Err(Error { code: HRESULT(0x00000000), message: "Der Vorgang wurde erfolgreich beendet." }) instead of Ok(USBDevice...)
![usberror](https://github.com/microsoft/windows-rs/assets/5970779/c9a75a02-0552-4e0b-ad0f-2402df297a41)

### Toolchain version/configuration

Default host: x86_64-pc-windows-msvc
rustup home:  C:\Users\V0640063\.rustup

installed toolchains
--------------------

stable-x86_64-pc-windows-msvc (default)
nightly-x86_64-pc-windows-msvc

active toolchain
----------------

stable-x86_64-pc-windows-msvc (default)
rustc 1.70.0 (90c541806 2023-05-31)

### Reproducible example

```rust
#[tokio::main]
async fn main() {
    let devices=windows::Devices::Enumeration::DeviceInformation::FindAllAsync().unwrap().await.unwrap()
            .into_iter().filter_map(|di|di.Id().ok()).collect::<Vec<_>>();
    let aiousbdevices=devices.iter().filter_map(|deviceid|windows::Devices::Usb::UsbDevice::FromIdAsync(deviceid).ok()).collect::<Vec<_>>();
    let mut usbdevices=Vec::new();
    for iao in aiousbdevices{
        usbdevices.push(iao.await);
    }
    println!("{:?}",usbdevices);
}
```

### Crate manifest

```toml
[dependencies]
tokio = {version = "1.28.2", features = ["rt","macros","rt-multi-thread"]}

[dependencies.windows]
version="0.48.0"
features = ["Devices",
            "Devices_Usb",
            "Foundation",
            "Foundation_Collections",
            "Devices_Enumeration"]
```

### Expected behavior

Get a Ok(USBDevice) from a plugged in  USB Device when using the corresponding ID

### Actual behavior

Got Err(Error { code: HRESULT(0x00000000), message: "Der Vorgang wurde erfolgreich beendet." })
