### ISSUE TITLE
Bug: Missing Win32_Graphics_DirectDraw feature

### ISSUE THREAD

**Issue by michaelwright235** [microsoft/windows-rs#2560]
### Which crate is this about?

windows-sys

### Crate version

0.48.0

### Summary

I'm trying to get access to the recently added WDK apis through `windows-sys` crate. For instance `windows_sys::Wdk::Foundation::DEVICE_OBJECT` structure is only available when a couple of features **(including Win32_Graphics_DirectDraw feature)** are enabled. However this one is missing from `windows-sys` Cargo.toml.

### Toolchain version/configuration

Default host: aarch64-pc-windows-msvc
rustup home:  C:\Users\michaelwright\.rustup

installed toolchains
--------------------

stable-aarch64-pc-windows-msvc
stable-x86_64-pc-windows-msvc
nightly-aarch64-pc-windows-msvc
nightly-x86_64-pc-windows-msvc (default)

installed targets for active toolchain
--------------------------------------

aarch64-pc-windows-msvc
x86_64-pc-windows-msvc

active toolchain
----------------

nightly-aarch64-pc-windows-msvc (overridden by 'C:\Users\michaelwright\Desktop\usbpcap-rs\rust-toolchain')
rustc 1.72.0-nightly (5ea666864 2023-06-27)

### Reproducible example

```rust
use windows_sys::Wdk::Foundation::DEVICE_OBJECT;
```

### Crate manifest

```toml
[dependencies]
windows-sys = {git = "https://github.com/microsoft/windows-rs/", features = ["Wdk_Foundation", "Wdk_Storage_FileSystem", "Wdk_System_SystemServices", "Win32_Graphics_DirectDraw", "Win32_Foundation", "Win32_Security", "Win32_System_Kernel", "Win32_System_Power", "Win32_System_WindowsProgramming"]}
```

### Expected behavior

A standart importing of `DEVICE_OBJECT` structure.

### Actual behavior

`cargo build` throws an error:

```
error: failed to select a version for `windows-sys`.
    ... required by package `usbpcap-rs v0.1.0 (C:\Users\michaelwright\Desktop\usbpcap-rs)`
versions that meet the requirements `*` (locked to 0.48.0) are: 0.48.0

the package `usbpcap-rs` depends on `windows-sys`, with features: `Win32_Graphics_DirectDraw` but `windows-sys` does not have these features.     


failed to select a version for `windows-sys` which could resolve this conflict
```
