### ISSUE TITLE
windows::Win32::UI does not have a SHELL package

### ISSUE THREAD

**Issue by bcdlbgm** [microsoft/windows-rs#2562]
windows::Win32::UI does not have a SHELL package, and I cannot find the ShellExecuteA function for use. I have checked my Cargo.toml and did not find any other issues, but I still cannot find the function call in the windows-rs library.

![image](https://github.com/microsoft/windows-rs/assets/45490024/ccd3c774-ad98-4b79-8c41-8b9503b5ed9f)
![image](https://github.com/microsoft/windows-rs/assets/45490024/3a2a590c-c274-43f9-93df-66d75f9db112)
![image](https://github.com/microsoft/windows-rs/assets/45490024/0e76ffc2-d5dd-4168-b85f-8d4b227439a3)

**Comment by riverar** [comment]
When reporting issues in the future, please fill out the bug form completely.

I can't reproduce the issue, this compiles and executes correctly. Perhaps your IDE is not refreshing correctly?

```toml
[package]
name = "app"
version = "0.0.0"
edition = "2018"
publish = false

[dependencies.windows]
version = "0.48"
features = [
    "Win32_Foundation",
    "Win32_UI_Shell",
    "Win32_UI_WindowsAndMessaging"
]

```

```rust
use windows::{s, Win32::UI::Shell::ShellExecuteA};

fn main() -> windows::core::Result<()> {
    unsafe {
        let _ = ShellExecuteA(
            None,
            None,
            s!("https://github.com/microsoft/windows-rs/issues/2562"),
            None,
            None,
            windows::Win32::UI::WindowsAndMessaging::SHOW_WINDOW_CMD(0),
        );
    }
    Ok(())
}

```
