### ISSUE TITLE
Calling the API to read serial port data fails

### ISSUE THREAD

**Issue by long-day** [microsoft/windows-rs#2690]
### Summary

I'm testing reading USB serial data through the window for rust API. With hard work, I can correctly print out the serial port information connected to the laptop, but I can't read data from it.
It will be:
![image](https://github.com/microsoft/windows-rs/assets/77600212/97f5b855-18cd-417a-be58-0b37452daa36)

### Crate manifest

```TOML
[package]
name = "helloworld"
version = "0.1.0"
edition = "2021"
build = "build.rs"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusb = "0.9"
serialport = "4.2"

libc = "0.2"

windows = { version = "0.51", features = [
    "Devices_Enumeration",
    "Foundation_Collections",
    "Devices_SerialCommunication",
    "Devices_Enumeration",
    "Foundation_Collections",
    "Storage_Streams",
] }

[build-dependencies]
cc = "1.0"
```

### Crate code

```Rust
fn main() {
    let a = DeviceInformation::FindAllAsyncAqsFilter(
        &SerialDevice::GetDeviceSelector().expect("err 1"),
    )
    .expect("err2");
    loop {
        let b = a.get();

        if let Ok(bb) = b {
            for ele in bb {
                println!(
                    "p: {} {} {} {:?}",
                    ele.Id().expect("err2"),
                    ele.IsEnabled().expect("err2-1"),
                    ele.Name().expect("err2-2"),
                    ele.Kind().expect("err2-2")
                );
                let device = SerialDevice::FromIdAsync(&ele.Id().expect("err3"))
                    .expect("err4")
                    .get()
                    .expect("err5");
                device.SetBaudRate(115_200).expect("e1");
                device.SetDataBits(8).expect("e2");
                device.SetStopBits(SerialStopBitCount::One).expect("e3");
                device.SetParity(SerialParity::None).expect("e4");
                let input_stream = device.InputStream().expect("err8");
                let reader = DataReader::CreateDataReader(&input_stream).expect("err10");

                for i in 1..4 {
                    std::thread::sleep(Duration::from_millis(100));
                    match reader.ReadByte() {
                        Ok(one_byte) => {
                            println!("No.{} :{}", i, one_byte);
                        }
                        Err(err) => {
                            println!("{}", err);
                        }
                    }
                }
            }
        }

        std::thread::sleep(Duration::from_secs(1));
    }
}
```
