### ISSUE TITLE
FreeMibTable returns ERROR_INVALID_FUNCTION

### ISSUE THREAD

**Issue by stormshield-kg** [microsoft/windows-rs#2712]
### Summary

The `windows::Win32::NetworkManagement::IpHelper::FreeMibTable` function frees the memory correctly, but always returns an error:
```
thread 'main' panicked at src\main.rs:12:41:
called `Result::unwrap()` on an `Err` value: Error { code: HRESULT(0x80070001), message: "Incorrect function." }
```
It seems that the function return `void` in the C API, but the wrapper in `windows-rs` returns a `Result`:
https://learn.microsoft.com/en-us/windows/win32/api/netioapi/nf-netioapi-freemibtable
https://learn.microsoft.com/en-us/windows/win32/api/netioapi/nf-netioapi-getunicastipaddresstable#examples

### Crate manifest

```TOML
[package]
name = "testwindows"
version = "0.1.0"
edition = "2021"

[dependencies]
windows = { version = "0.52.0", features = [
    "Win32_NetworkManagement_IpHelper",
    "Win32_Foundation",
    "Win32_NetworkManagement_Ndis",
    "Win32_Networking_WinSock",
] }
```

### Crate code

```Rust
use windows::Win32::{
    NetworkManagement::IpHelper::{
        FreeMibTable, GetUnicastIpAddressTable, MIB_UNICASTIPADDRESS_TABLE,
    },
    Networking::WinSock::AF_UNSPEC,
};

fn main() {
    unsafe {
        let mut ip_table_ptr: *mut MIB_UNICASTIPADDRESS_TABLE = std::ptr::null_mut();
        GetUnicastIpAddressTable(AF_UNSPEC, &mut ip_table_ptr as *mut _).unwrap();
        FreeMibTable(ip_table_ptr as _).unwrap();
    }
}
```
