### ISSUE TITLE
mismatched exception constants

### ISSUE THREAD

**Issue by godfearingman** [microsoft/windows-rs#2721]
### Summary

Was in the midst of writing vectored exception handler and realised my handler wasn't functioning as it should when it came to returns. it would exit with an unhandled software bp. I checked the return constants and realised that the values in comparison with C++ macro's were different.

```cpp
// Defined values for the exception filter expression
#define EXCEPTION_EXECUTE_HANDLER      1
#define EXCEPTION_CONTINUE_SEARCH      0
#define EXCEPTION_CONTINUE_EXECUTION (-1)
```
vs
```rs
pub const ExceptionContinueExecution: EXCEPTION_DISPOSITION = EXCEPTION_DISPOSITION(0i32);
pub const ExceptionContinueSearch: EXCEPTION_DISPOSITION = EXCEPTION_DISPOSITION(1i32);
```

### Crate manifest

```TOML
[dependencies.windows]
version = "0.52.0"
features = ["Win32_Foundation", "Win32_System_Threading", "Win32_System_Diagnostics_Debug", "Win32_System_Diagnostics_ToolHelp", "Win32_System_Memory", "Win32_Security", "Win32_System_Kernel", "Win32_UI_WindowsAndMessaging", "Win32_System_LibraryLoader", "Win32_System_WindowsProgramming"]
```

### Crate code

```Rust
/// Define our vectored exception handler
pub unsafe extern "system" fn exception_handler(exception_info: *mut EXCEPTION_POINTERS) -> i32 {
    if (*(*exception_info).ExceptionRecord).ExceptionCode == EXCEPTION_BREAKPOINT {
        println!("Hit breakpoint");
        return ExceptionContinueExecution.0
    }
    ExceptionContinueSearch.0
}

//...
unsafe { AddVectoredExceptionHandler(1, Some(exception_handler)); }
```
