### ISSUE TITLE
ReplaceFileW → could not find `Storage` in `Win32`

### ISSUE THREAD

**Issue by Coding-Badly** [microsoft/windows-rs#2746]
### Summary

[According to the documentation](https://microsoft.github.io/windows-docs-rs/doc/windows/Win32/Storage/FileSystem/fn.ReplaceFileW.html), feature `Win32_Foundation` is required for `ReplaceFileW`.  That is apparently not enough.  The `Win32_Storage_FileSystem` feature is also required.

### Crate manifest

```TOML
[package]
name = "bug_001"
version = "0.1.0"
edition = "2021"

[dependencies]
windows = { version = "0.52.0", features = ["Win32_Foundation"] }
```

### Crate code

```Rust
use windows::Win32::Storage::FileSystem::ReplaceFileW;

fn main() {
    println!("Hello, world!");
}
```

### Error
```
error[E0433]: failed to resolve: could not find `Storage` in `Win32`
 --> src\main.rs:1:21
  |
1 | use windows::Win32::Storage::FileSystem::ReplaceFileW;
  |                     ^^^^^^^ could not find `Storage` in `Win32`
```
