### ISSUE TITLE
Windows.Graphics.Display.DisplayServices: Class not registered HRESULT(0x80040154)

### ISSUE THREAD

**Issue by Niwo04** [microsoft/windows-rs#2763]
### Summary

rustc version: 1.74.1

I'm trying to use the Windows.Graphics.Capture namespace (https://learn.microsoft.com/en-us/uwp/api/windows.graphics.capture?view=winrt-22621) for a screen capture application and first I want to get a list of all available screens using the Windows.Graphics.Display.DisplayServices class' function FindAll (https://learn.microsoft.com/en-us/uwp/api/windows.graphics.display.displayservices.findall?view=winrt-22621#windows-graphics-display-displayservices-findall).

But when I run the provided example I get the error variant saying: Class not registered.

I hope this will be fixed eventually or that someone can tell me what I'm doing wrong.

### Crate manifest

```TOML
[package]
name = "windows_test"
version = "0.1.0"
edition = "2021"

[dependencies]
windows = { version = "0.52.0", features = ["Graphics", "Graphics_Display"] }
```

### Crate code

```Rust
fn main() {
    let test = windows::Graphics::Display::DisplayServices::FindAll();
    match test {
        Ok(_) => println!("ok"),
        Err(err) => println!("{:?}", err)
    }
}
```
