### ISSUE TITLE
ThreadPoolWorker example missing feature

### ISSUE THREAD

**Issue by jgardona** [microsoft/windows-rs#2772]
### Summary

Hello, good morning.
The following example has a missing feature, that leads to compilation failure. We need to add **Win32_Foundation**, and this will fix this issue.
https://github.com/microsoft/windows-rs/tree/master/crates/samples/windows/thread_pool_work

### Crate manifest

```TOML
[package]
name = "sample_thread_pool_work"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.windows]
path = "../../../libs/windows"
features = [
    "Win32_System_Threading",
]
```

### Crate code

```Rust
use windows::{core::Result, Win32::System::Threading::*};

static COUNTER: std::sync::RwLock<i32> = std::sync::RwLock::new(0);

fn main() -> Result<()> {
    unsafe {
        let work = CreateThreadpoolWork(Some(callback), None, None)?;

        for _ in 0..10 {
            SubmitThreadpoolWork(work);
        }

        WaitForThreadpoolWorkCallbacks(work, false);
    }

    let counter = COUNTER.read().unwrap();
    println!("counter: {}", *counter);
    Ok(())
}

extern "system" fn callback(_: PTP_CALLBACK_INSTANCE, _: *mut std::ffi::c_void, _: PTP_WORK) {
    let mut counter = COUNTER.write().unwrap();
    *counter += 1;
}
```
