### ISSUE TITLE
windows::Win32::Foundation::LocalFree returns Err(_) on Success

### ISSUE THREAD

**Issue by hieronymusma** [microsoft/windows-rs#2796]
### Summary

LocalFree returns NULL on success and a handle to the memory object on error [(LocalFree)](https://learn.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-localfree). However, because the return type of LocalFree is `HLOCAL`,  the returned result is checked for NULL and then an Err(\_) is returned instead of a Ok(\_).

The provided example shows this behavior by using the question mark operator. The example fails although it should succeed.

Is there a way to customize this behavior such that a Ok(\_) result is returned?

Thank you!

### Crate manifest

```TOML
[package]
name = "bug-local-free"
version = "0.1.0"
edition = "2021"

[dependencies]
windows = { version = "0.52.0", features = ["Win32_Foundation", "Win32_System", "Win32_System_Memory"] }
```

### Crate code

```Rust
use windows::Win32::{
    Foundation::LocalFree,
    System::Memory::{LocalAlloc, LPTR},
};

fn main() -> Result<(), Box<dyn std::error::Error>> {
    unsafe {
        let allocation = LocalAlloc(LPTR, 1)?;
        LocalFree(allocation)?;
    }
    Ok(())
}
```
