### ISSUE TITLE
The file name is too long

### ISSUE THREAD

**Issue by irvingoujAtDevolution** [microsoft/windows-rs#2832]
### Summary

Trying to duplicate the ipconfig.c  using rust, see[ the source code here](https://github.com/microsoft/Windows-classic-samples/blob/main/Samples/Win7Samples/netds/iphelp/ipconfig/IPConfig.c)

however, though the original c file runing successfully, the rust version fails with 
```
Error: The file name is too long. (0x8007006F)
```

### Crate manifest

```TOML
[package]
name = "windows-dns-api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.79"
windows = { version = "0.52.0", features = ["Win32_NetworkManagement_IpHelper", "Win32_Foundation", "System", "Win32_System_Memory", "Win32", "Win32_System"] }
```

### Crate code

```Rust
fn main() -> anyhow::Result<()> {
    unsafe {
        // First call to GetNetworkParams to get the required buffer size
        let mut buffer_size = 0;
        GetNetworkParams(None, &mut buffer_size)?;
        dbg!(buffer_size);
        // Allocate buffer for the FIXED_INFO structure
        let fixed_info_buffer = Memory::GlobalAlloc(windows::Win32::System::Memory::GPTR, buffer_size as _)?;
        dbg!(fixed_info_buffer);
        }
  }
```

please let me know what other infomrations you need to resolve this issue
