### ISSUE TITLE
Error 0x80070032 when calling COM from Rust

### ISSUE THREAD

**Issue by daladim** [microsoft/windows-rs#2875]
### Summary

Hello,
I can successfully use the Location COM API using C++, but I don't understand why the exact same code in Rust fails with a `0x80070032 (ERROR_NOT_SUPPORTED)` error.
Google does not help, as this error may not be Location API specific, and [the official documentation](https://learn.microsoft.com/en-us/windows/win32/api/locationapi/nf-locationapi-ilocation-getdesiredaccuracy) does not list this error as a possible return value.

Do you what I'm doing wrong? Could this be a windows-rs issue?

The linked Rust code runs with the following output
```
C:\src\com>cargo run
     Running `target\debug\com.exe`
Inited COM library Ok(())
Accuracy is Err(Error { code: HRESULT(0x80070032), message: "Cette demande n’est pas prise en charge." })
```

On the other hand, a (seemingly) perfectly equivalent `repro.cpp` C++ code works.
```
#include <windows.h>
#include <stdio.h>
#include <LocationApi.h>

#pragma comment(lib,"Ole32.lib")        // for COM functions
#pragma comment(lib,"LocationAPI.lib")


int main() {
    HRESULT hr = CoInitializeEx(NULL, COINIT_APARTMENTTHREADED | COINIT_DISABLE_OLE1DDE);
    printf("[%x]\tinited COM\n", hr);

    ILocation *pLocation; // This is the main Location interface.
    hr = CoCreateInstance(CLSID_Location, NULL, CLSCTX_ALL, IID_PPV_ARGS(&pLocation));
    printf("[%x]\tCreated instance\n", hr);

    LOCATION_DESIRED_ACCURACY desiredAccuracy = LOCATION_DESIRED_ACCURACY_HIGH;
    hr = pLocation->GetDesiredAccuracy(IID_ILatLongReport, &desiredAccuracy);
    printf("[%x]\tCurrent accuracy: %x\n", hr, desiredAccuracy);

    CoUninitialize();
    return 0;
}
```

In a "Developer Command prompt for VS2022", one can run:
```
C:\src\com_cpp>cl repro.cpp
[...]

C:\src\com_cpp>repro.cpp
[0]     inited COM
[0]     Created instance
[0]     Current accuracy: 0
```

(I have checked, the GUIDs to create the classes are the same, so that can't be a source of the issue)

Thanks!

### Crate manifest

```TOML
[package]
name = "com"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
windows = { version = "0.52.0", features = [
    "Win32_System_Com",
    "Win32_Foundation",
    "Win32_Devices",
    "Win32_Devices_Geolocation",
    "Win32_Devices_Sensors",
] }
```

### Crate code

```Rust
// This does not make a change
// (but I checked because maybe Windows has different location (and privacy) settings for desktop, GUI, or console apps
// #![windows_subsystem = "windows"]

use windows::Win32::Devices::Geolocation::{
    Location,
    LatLongReport,
    ILocation,
};
use windows::Win32::Foundation::HWND;
use windows::Win32::System::Com::{
    CoInitializeEx,
    CoCreateInstance,
    CLSCTX_ALL,
    COINIT_APARTMENTTHREADED,
    COINIT_DISABLE_OLE1DDE,
};
use windows::core::GUID;


fn main() {
    let res = unsafe {
        CoInitializeEx(None, COINIT_APARTMENTTHREADED | COINIT_DISABLE_OLE1DDE)
    };
    println!("Inited COM library {res:?}");
   
    let location = unsafe{
        CoCreateInstance::<_, ILocation>(
            &Location as *const _,
            None,
            CLSCTX_ALL,
        )
    }.unwrap();

    let res = unsafe {
        location.GetDesiredAccuracy(&LatLongReport as *const GUID)
    };
    println!("Accuracy is {res:?}");
}
```
