### ISSUE TITLE
`SHOpenFolderAndSelectItems` missing in `windows-sys`

### ISSUE THREAD

**Issue by amrbashir** [microsoft/windows-rs#2885]
### Summary

Seems like `SHOpenFolderAndSelectItems` is not present in `windows-sys` while available in the full `windows` crate

### Crate manifest

```TOML
0.52.0
```

**Comment by riverar** [comment]
Already fixed as of https://github.com/microsoft/windows-rs/pull/2804, should be fixed in `windows-sys` 0.53. If you want, you can point to the repository in your dependencies.

```toml
[dependencies.windows-sys]
git = "https://github.com/microsoft/windows-rs/"
features = [
    "Win32_UI_Shell_Common"
]
```

@kennykerr Is a 0.53 -sys crate release planned?
