### ISSUE TITLE
Unable to wrap MEMORY_BASIC_INFORMATION in a Mutex

### ISSUE THREAD

**Issue by TallonIV** [microsoft/windows-rs#2893]
### Summary

I am trying to use the windows crate with flutter_rust_bridge _https://github.com/fzyzcjy/flutter_rust_bridge_. In my code I use the struct MEMORY_BASIC_INFORMATION, one of the conditions to use flutter rust bridge is that the struct has to be sent between threads safely. When I compile my app I get the next error
```
389  | / flutter_rust_bridge::frb_generated_moi_arc_impl_value!(
390  | |     flutter_rust_bridge::for_generated::rust_async::RwLock<Mutex<MEMORY_BASIC_INFORMATION>>
391  | | );
     | |_^ `*mut c_void` cannot be sent between threads safely
```
I have tried to wrap the MEMORY_BASIC_INFORMATION in a Mutex but I still get the same error, like it can be seen in the next discussion _https://github.com/fzyzcjy/flutter_rust_bridge/discussions/1787_

### Crate manifest

```TOML
[package]
name = "rust_lib"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
flutter_rust_bridge = "=2.0.0-dev.25"
windows = { version = "0.53.0", features = ["Win32_Foundation", "Win32_System", "Win32_System_ProcessStatus", "Win32_System_Threading", "Win32_System_Diagnostics", "Win32_System_Diagnostics_Debug", "Win32_System_Memory", "Wdk_System_SystemServices"] }
```

### Crate code

```Rust
pub use std::sync::Mutex;
pub use windows::Win32::System::Memory::MEMORY_BASIC_INFORMATION;
use windows::Win32::System::Memory::VirtualQueryEx;

pub fn memory_regions() -> io::Result<Mutex<MEMORY_BASIC_INFORMATION>>{
    let mut info = std::mem::MaybeUninit::uninit();
    let handle =open_handle(4496);
    let written = unsafe {
        VirtualQueryEx(
            handle,
            Some(std::ptr::null()),
            info.as_mut_ptr(),
            std::mem::size_of::<MEMORY_BASIC_INFORMATION>(),
        )
    };
    if written == 0{
        return Err(std::io::Error::last_os_error())
    }
    close_handle(handle);
    unsafe { Ok(Mutex::new(info.assume_init())) }
}
```
