### ISSUE TITLE
Code blocks after calling DeviceInfomation::FindAllAsync() greater than 0.52.0 version

### ISSUE THREAD

**Issue by Goolnn** [microsoft/windows-rs#2922]
### Summary

When the version is greater than 0.52.0, the code will permanently block when find devices' infomation. But below or equal to 0.52.0 do not blocks. I can reliably reproduce the problem on my computer.

### Crate manifest

```TOML
[package]
name = "project"
version = "0.1.0"
edition = "2021"

[dependencies]
# In version 0.52.0 or below have no problem
windows = { version = "0.54.0", features = [
  "Foundation_Collections",
  "Devices_Enumeration",
  "Devices_Bluetooth",
] }
```

### Crate code

```Rust
use windows::Devices::Enumeration::DeviceInformation;
use windows::Devices::Bluetooth::BluetoothLEDevice;

fn main() {
  let selector = BluetoothLEDevice::GetDeviceSelectorFromPairingState(true).unwrap();
  let collection = DeviceInformation::FindAllAsyncAqsFilter(&selector).unwrap().get().unwrap();

  for device_info in collection {
    println!("{device_info:?}");
  }
}
```
