### ISSUE TITLE
Bug: Errors require `HRESULT(x).into()`

### ISSUE THREAD

**Issue by RivenSkaye** [microsoft/windows-rs#2936]
### Summary

Crate(s): `windows`, `windows-result`
Version: 0.54 (latest on crates.io at the time of writing)

Trying to instantiate an error from `windows-result` is currently An Experience, to say the least. The current implementation downright breaks when providing the types listed in the function signature, and probably due to the `#[repr(transparent)]` the error message provided by `rustc` steers you further off from working code as it makes you go back and forth between `HRESULT` and `i32`.
This doesn't feel ergonomic, and more importantly the type resolution provided is broken to the point it's actively confusing. I'll open an issue over at rustc as well for the type resolution confusion here, but it feels like it belongs here as well.

![image](https://github.com/microsoft/windows-rs/assets/14993038/4a413fdf-c311-4d0f-9c8f-0ebf2622a059)

### Crate manifest

```TOML
[package]
    edition = "2021"
    license = "MIT OR Apache-2.0"
    name    = "repro"
    version = "0.1.0"

[dependencies]
    # don't know which ones are relevant by heart and the feature selection tool seems to be a version or two behind
    # I suppose it only takes Foundation for Error and HRESULT?
    windows = {version = "0.54", features = [
        "Win32_Foundation"
    ]}
```

### Crate code

```Rust
use windows::core::{Error as WErr, HRESULT};

fn some_res(succeed: i32) -> Result<(), WErr> {
    match succeed {
        1 => Err(WErr::new(HRESULT(succeed), "This doesn't work")), // Error: expected an i32
        2 => Err(WErr::new(succeed, "Neither does this")), // Error: expected a HRESULT
        3 => Err(WErr::new(succeed.into(), "Nor this")), // Error: the trait bound `HRESULT: From<i32>` is not satisfied
        255 => Err(WErr::new(255.into(), "And this fails too")), // Error: the trait bound `HRESULT: From<{integer}>` is not satisfied
        0 => Ok(()),
        _ => Err(Werr::new(HRESULT(succeed).into(), "This is what you need for it to work")),
    }
}

fn main() {
    some_res(1).expect("If you get here, compilation succeeded")
}
```
