### ISSUE TITLE
Can't see feature requirement for methods

### ISSUE THREAD

**Issue by Cinimajig** [microsoft/windows-rs#3123]
### Summary

I'll use [`INetwork::GetName`](https://learn.microsoft.com/en-us/windows/win32/api/netlistmgr/nf-netlistmgr-inetwork-getname) as en example.

I was trying to call the above method on the `INetwork` interface, but it does not exist. I then looked up the function on [windows-docs-rs](https://microsoft.github.io/windows-docs-rs/doc/windows/Win32/Networking/NetworkListManager/struct.INetwork.html#method.GetName), but I cant see what feature I'm missing to use it.

![Image of windows-docs-rs](https://github.com/microsoft/windows-rs/assets/39052490/d83050fb-7cb0-4171-9726-77b032a0f1ec)

I then tried to find the interface on the feature searcher, but it does not mention methods, only the interface itself... How are we supposed to find this information?

### Crate manifest

```TOML
[package]
name = "networklist"
version = "0.1.0"
edition = "2021"

[profile.release]
lto = true
codegen-units = 1
strip = true

[dependencies]
windows = { version = "0.57.0", features = [
    "Win32_Foundation",
    "Win32_System_Com",
    "Win32_System_LibraryLoader",
    "Win32_UI_WindowsAndMessaging",
    "Win32_Graphics_Gdi",
    "Win32_NetworkManagement_IpHelper",
    "Win32_Networking_WinInet",
    "Win32_Networking_NetworkListManager",
] }
```

### Crate code

```Rust
fn enum_network() -> windows::core::Result<()> {
    use windows::Win32::{Networking::NetworkListManager::*, System::Com::*};

    unsafe {
        CoInitializeEx(None, COINIT_APARTMENTTHREADED).ok()?;
        let manager: INetworkListManager = CoCreateInstance(&NetworkListManager, None, CLSCTX_ALL)?;

        let enumer = manager.GetNetworkConnections()?;

        let mut conn: [Option<INetworkConnection>; 10] = Default::default();
        let mut amount: u32 = 10;
        while let Ok(_) = enumer.Next(&mut conn, Some(&mut amount)) {
            if amount == 0 {
                break;
            }
            for connection in &conn {
                match connection {
                    Some(connection) => {
                        let network = connection.GetNetwork()?;

                        let cat = network.GetCategory()?;
                        let description = network.GetDescription()?;
                        let name = connection.GetName()?; // <-- Error here

                        println!("Network name : {}", name);
                        println!("Description  : {}", description);
                        println!("Category     : {}", cat.0);
                    }
                    None => (),
                }
            }
        }

        Ok(())
    }
}
```
