### ISSUE TITLE
Windows-core incorrectly propagates the std feature to subcrates

### ISSUE THREAD

**Issue by Intege-rs** [microsoft/windows-rs#3163]
### Summary

[Windows-core](https://github.com/microsoft/windows-rs/blob/master/crates/libs/core/Cargo.toml) always enables the std feature on [Windows-strings](https://github.com/microsoft/windows-rs/blob/master/crates/libs/strings/Cargo.toml) and [Windows-results](https://github.com/microsoft/windows-rs/blob/master/crates/libs/result/Cargo.toml)

### Crate manifest

```TOML
[package]
name = "scratch"
version = "0.1.0"
edition = "2021"

[dependencies.windows]
version = "0.58.0"
default-features = false
features = []
```

### Crate code

```Rust
# build.rs
fn main() {
    println!("cargo:rustc-link-arg=/SubSystem:Console");
    println!("cargo:rustc-link-arg=/ENTRY:main");
}

# main.rs
#![no_std] #![no_main]

#[no_mangle]
extern "C" fn main() {
    // result incorrectly re-imports std into a no-std project
    let _ = windows::core::HRESULT(0);
}

// found duplicate lang item `panic_impl`
#[cfg_attr(not(test), panic_handler)]
fn _panic(_: &core::panic::PanicInfo) -> ! {
    loop {}
}
```
