### ISSUE TITLE
Unable to implement IMFAsyncCallback

### ISSUE THREAD

**Issue by mycrl** [microsoft/windows-rs#3194]
### Summary

According to https://github.com/microsoft/windows-rs/pull/3065, I tried to implement `IMFAsyncCallback`, but obviously, an error occurred and I don't know where the problem is.

```
error[E0405]: cannot find trait `IMFAsyncCallback_Impl` in this scope
 --> mft\src\lib.rs:8:6
  |
8 | impl IMFAsyncCallback_Impl for VideoProcessorAsyncCallback_Impl {
  |      ^^^^^^^^^^^^^^^^^^^^^ not found in this scope
```

### Crate manifest

```TOML
[package]
name = "mft"
version = "0.1.0"
edition = "2021"

[target.'cfg(target_os = "windows")'.dependencies]
windows-core = "0.58.0"

[target.'cfg(target_os = "windows")'.dependencies.windows]
version = "0.58.0"
features = [
    "implement",
    "Win32_System_Com", 
    "Win32_System_Com_StructuredStorage",
    "Win32_Media", 
    "Win32_Media_MediaFoundation", 
]
```

### Crate code

```Rust
use windows::Win32::Media::MediaFoundation::{IMFAsyncResult, MFASYNC_BLOCKING_CALLBACK, MFASYNC_CALLBACK_QUEUE_MULTITHREADED};
use windows_core::{implement, Param};

#[implement(windows::Win32::Media::MediaFoundation::IMFAsyncCallback)]
pub struct VideoProcessorAsyncCallback;

#[allow(non_snake_case)]
impl IMFAsyncCallback_Impl for VideoProcessorAsyncCallback_Impl {
    unsafe fn GetParameters(
        &self,
        pdwflags: *mut u32,
        pdwqueue: *mut u32,
    ) -> windows::core::Result<()> {
        *pdwflags = MFASYNC_BLOCKING_CALLBACK;
        *pdwqueue = MFASYNC_CALLBACK_QUEUE_MULTITHREADED;

        Ok(())
    }

    unsafe fn Invoke<T>(
        &self,
        pasyncresult: T,
    ) -> windows::core::Result<()>
    where 
        T: Param<IMFAsyncResult>, 
    {
        Ok(())
    }
}
```

**Comment by riverar** [comment]
You're missing a use declaration for the `IMFAsyncCallback_Impl` type (i.e. `use windows::Win32::Media::MediaFoundation::IMFAsyncCallback_Impl`). Fixing that gets you to other errors related to generics, etc.

Here's a working skeleton:

```rust
#![allow(unused)]

use windows::Win32::Media::MediaFoundation::{
    IMFAsyncCallback, IMFAsyncCallback_Impl, IMFAsyncResult,
};
use windows_core::implement;

#[implement(IMFAsyncCallback)]
pub struct Foo;

impl IMFAsyncCallback_Impl for Foo_Impl {
    fn GetParameters(&self, pdwflags: *mut u32, pdwqueue: *mut u32) -> windows_core::Result<()> {
        todo!()
    }

    fn Invoke(&self, pasyncresult: Option<&IMFAsyncResult>) -> windows_core::Result<()> {
        todo!()
    }
}

fn main() -> windows::core::Result<()> {
    Ok(())
}
```

```toml
[package]
name = "app"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.windows]
version = "0.58.0"
features = [
    "implement",
    "Win32_Foundation",
    "Win32_Media_MediaFoundation",
]

[dependencies.windows-core]
version = "0.58.0"
```
