### ISSUE TITLE
WSASetEvent and WSAResetEvent should take a WSAEVENT instead of a HANDLE

### ISSUE THREAD

**Issue by eduardosm** [microsoft/windows-rs#3195]
### Summary

Functions `WSASetEvent` and `WSAResetEvent` are defined in windows-sys as:

```rust
pub unsafe extern "system" fn WSAResetEvent(hevent: HANDLE) -> BOOL

pub unsafe extern "system" fn WSASetEvent(hevent: HANDLE) -> BOOL
```

However, in their original C definitions they take a `WSAEVENT` instead of a `HANDLE`:

```c
BOOL WSAAPI WSASetEvent(
  [in] WSAEVENT hEvent
);

BOOL WSAAPI WSAResetEvent(
  [in] WSAEVENT hEvent
);
```

### Crate manifest

```TOML
[dependencies.windows-sys]
version = "0.59.0"
features = ["Win32_Networking_WinSock"]
```

### Crate code

```Rust
use windows_sys::Win32::Networking::WinSock;

unsafe {
    let event = WinSock::WSACreateEvent();
    WinSock::WSASetEvent(event); // compilation error due to mismatching types
}
```
