### ISSUE TITLE
windows crate compiling process will be blocked as malware behavior for rustc by Trend Micro Apex One

### ISSUE THREAD

**Issue by kin789246** [microsoft/windows-rs#3217]
### Summary

windows crate compiling process will be blocked as malware behavior for rustc, but windows-sys crate will pass the compiling process.

### Crate manifest

```TOML
[package]
name = "test-chcp"
version = "0.1.0"
edition = "2021"

[dependencies.windows]
version = "0.58.0"
```

### Crate code

```Rust
n/a
```
