### ISSUE TITLE
`windows-bindgen` doesn't error on unused filters

### ISSUE THREAD

**Issue by kennykerr** [microsoft/windows-rs#3244]
### Summary

We don't have a failure test for this scenario so this slipped in at some point. 

### Crate manifest

```toml
[build-dependencies.windows-bindgen]
version = "0.58"
```

### Crate code

```Rust
fn main() {
    windows_bindgen::bindgen(["--out", "src/bindings.rs", "--filter", "Not.Found"]).unwrap();
}
```
