### ISSUE TITLE
`GetThreadDpiAwarenessContext()` returns unexpected `DPI_AWARENESS_CONTEXT`

### ISSUE THREAD

**Issue by jh-go** [microsoft/windows-rs#3348]
### Summary

Hello,

the value returned by `GetThreadDpiAwarenessContext()` does not equal the `DPI_AWARENESS_CONTEXT` previously set with `SetThreadDpiAwarenessContext()`. The latter call seems to have been successful, however, as the window shows the desired DPI behavior. Please note that it makes no difference whether the DPI behavior is set at runtime or in the application manifest. Observed on Windows 11 Build 22631.

### Crate manifest

```TOML
[package]
name = "demo"
version = "0.1.0"
edition = "2021"

[dependencies.windows]
version = "0.58.0"
features = [
    "Win32_UI_HiDpi",
]
```

### Crate code

```Rust
// main.rs
fn main() {
    let requested_context = windows::Win32::UI::HiDpi::DPI_AWARENESS_CONTEXT_PER_MONITOR_AWARE_V2;

    unsafe { 
        windows::Win32::UI::HiDpi::SetThreadDpiAwarenessContext(requested_context);
    }
    let actual_context = unsafe { 
        windows::Win32::UI::HiDpi::GetThreadDpiAwarenessContext()
    };

    if requested_context != actual_context {
        println!("DPI awareness context: requested: {}, got: {}", 
            requested_context.0 as i32, actual_context.0 as i32);
    }

    // Prints: DPI awareness context: requested: -4, got: 34
}
```
