### ISSUE TITLE
`Package.GetAppInstallerInfo()` returns Err with HRESULT `0x00000000`

### ISSUE THREAD

**Issue by Aditeya** [microsoft/windows-rs#3363]
### Summary

`Package.GetAppInstalllerInfo()` returns a confusing error:

```
Failed to get AppInstallerInfo for name: Paint publisher: Microsoft Corporation : Error {
    code: HRESULT(0x00000000),
    message: "The operation completed successfully.",
}
```

I've tried this on windows 10 and 11 and all `Packages` that `FindPackages` returns gives the error when calling `GetAppInstallerInfo`.

### Crate manifest

```TOML
[package]
name = "winpacman"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.94"
tabled = "0.17.0"
windows = { version = "0.58.0", features = ["Management", "ApplicationModel", "Management_Deployment", "Foundation_Collections"] }
```

### Crate code

```Rust
use anyhow::Context;
use tabled::{Table, Tabled};
use windows::ApplicationModel::{AppInstallerInfo, Package, PackageVersion};
use windows::Management::Deployment::PackageManager;

#[derive(Tabled, Debug)]
struct App {
    pub name: String,
    pub publisher: String,
    pub version: String,
}

fn main() -> anyhow::Result<()> {
    let pacman = PackageManager::new().context("Failed to get Package Manager")?;
    let packages = pacman
        .FindPackages()
        .context("Failed to get all packages")?;
    let mut apps = vec![];
    for package in packages {
        if package
            .IsFramework()
            .context("Failed to check if IsFramework")?
        {
            continue;
        }
        let name = package
            .DisplayName()
            .map(|h| h.to_string_lossy())
            .unwrap_or_default();
        let publisher = package
            .PublisherDisplayName()
            .map(|h| h.to_string_lossy())
            .unwrap_or_default();
        let version = match package.GetAppInstallerInfo() {
            Ok(a) => {
                let version = a.Version().context("Failed to get version")?;
                format!("{:?}", version)
            }
            Err(e) => {
                eprintln!("Failed to get AppInstallerInfo for name: {name} publisher: {publisher} : {e:#?}");
                "".to_string()
            }
        };
        let version = format!("{:?}", version);
        apps.push(App {
            name,
            publisher,
            version,
        });
    }

    let table = Table::new(&apps).to_string();
    println!("{table}");

    Ok(())
}
```
