### ISSUE TITLE
Unexpected Behavior and `STATUS_HEAP_CORRUPTION` Error While Calling `WNetGetUniversalNameW

### ISSUE THREAD

**Issue by ajaykumargdr** [microsoft/windows-rs#3410]
### Summary

While calling the unsafe function `WNetGetUniversalNameW`, I'm getting various unexpected behaviors and errors. 

## **Environment Details**

- **Operating System:** Windows (x86_64-pc-windows-msvc)  
- **Rust Version:**  
  - Default toolchain: `stable-x86_64-pc-windows-msvc`
  - Rustc version: `rustc 1.83.0`

#### **1. Unexpected Behavior When Using `WNetGetUniversalNameW`**

- **Behavior:**  
  Various issues occur when using `WNetGetUniversalNameW`, including:
  - Produces wrong output in debug run and test (output: `\\`).
  - Works correctly in release build (output: `\\OFFICE_10\AjayDrive`), but fails in release test (`cargo test -r`).
  - Infinite loops in release builds when the function is called inside a loop.
  - Discrepancies between debug and release builds.

**Code Snippet:**

```rust
fn get_share_path_fail(){
    let path = widestring::U16String::from_str("E:\0");
    let path = PCWSTR(path.as_ptr());

    let mut uname_info: UNIVERSAL_NAME_INFOW = UNIVERSAL_NAME_INFOW::default();
    let mut size = 1024u32;

    unsafe {
        let result = WNetGetUniversalNameW(
            path,
            UNIVERSAL_NAME_INFO_LEVEL,
            &mut uname_info as *const _ as _,
            &mut size as *mut u32,
        );

        println!(
            "WNetGetConnectionW {} {:?}",
            result.0,
            uname_info.lpUniversalName.to_string()
        );
    };
}
```

---

#### **2. `STATUS_HEAP_CORRUPTION` in Release Builds**

- **Behavior:**  
  Returning the value works fine in debug mode but causes a `STATUS_HEAP_CORRUPTION` error in release builds.

**Code Snippet:**

```rust
fn get_share_path_fail_1(path: &str) -> String {
    let path_null_terminated = format!("{path}\0");
    let path_ws = widestring::U16String::from_str(&path_null_terminated);
    let path = PCWSTR(path_ws.as_ptr());

    let mut uname_info: UNIVERSAL_NAME_INFOW = UNIVERSAL_NAME_INFOW::default();
    let mut size = 1024u32;

    unsafe {
        let _result = WNetGetUniversalNameW(
            path,
            UNIVERSAL_NAME_INFO_LEVEL,
            &mut uname_info as *const _ as _,
            &mut size as *mut u32,
        );

        // * uncommenting following code leads more bug, outputs just "\\"
        // if _result != NO_ERROR {
        //     return String::new()
        // }

        return uname_info.lpUniversalName.to_string().unwrap_or_default();
    };
}
```

---

#### **3. Unused Variable Leading to `STATUS_HEAP_CORRUPTION`**

- **Behavior:**  
  Leaving the variable `let unc_share_path = String::new();` unused results in a `STATUS_HEAP_CORRUPTION` error in debug mode but runs fine in release mode.

**Code Snippet:**

```rust
fn get_share_path_fail_2(path: &str) {
    let path = widestring::U16String::from_str(&format!("{path}\0"));
    let path = PCWSTR(path.as_ptr());

    let mut uname_info: UNIVERSAL_NAME_INFOW = UNIVERSAL_NAME_INFOW::default();
    let mut size = 1024u32;

    let unc_share_path = String::new(); // fixes the issue if I comment this code

    unsafe {
        let _ = WNetGetUniversalNameW(
            path,
            UNIVERSAL_NAME_INFO_LEVEL,
            &mut uname_info as *const _ as _,
            &mut size as *mut u32,
        );
    };
}
```

From my observations, the errors and unexpected behaviors seem to arise only when using the unsafe API function WNetGetUniversalNameW (since commenting the function call clears the bugs). However, I am uncertain whether these issues are due to incorrect handling of unsafe code on my part or if there are intrinsic problems with the API usage.

### Crate manifest

```TOML
[package]
name = "front_end_drive"
version = "0.1.0"
edition = "2021"

[dependencies]
windows = { git = "https://github.com/microsoft/windows-rs", package = "windows", features = [
    "Win32",
    ...
    "Win32_NetworkManagement_WNet"
] }
widestring = { version = "1.1.0", default-features = false, features = ["alloc"] }

[dependencies.winapi]
git = "https://github.com/Trantect/winapi-rs.git"
branch = "feature/km"
features = ["ntstatus"]
```

### Crate code

```Rust

```
