### ISSUE TITLE
Success messages from `Dxc::DxcOperationResult::GetResult` and `GetErrorBuffer` are returned as errors

### ISSUE THREAD

**Issue by heavyrain266** [microsoft/windows-rs#3434]
### Summary

Hey, while working with `dxc` bindings, noticed that `GetResult` and `GetErrorBuffer` from `IDxcOperationResult` are resulting in error with success message:

```
Err(Error { code: HRESULT(0x00000000), message: "The operation completed successfully." })
```

and then `GetStatus` returns `Ok(HRESULT(0x00000000))` for each validated shader

### Crate manifest

```TOML
[package]
name = "test_dx12"
version = "0.1.0"
edition = "2021"

[dependencies.windows]
version = "0.59.0"
default-features = false
features = [
    "Win32_Graphics_Direct3D_Dxc",
]
```

### Crate code

```Rust
use windows::{
	core::{Interface, Result},
	Win32::Graphics::Direct3D::Dxc as dxc,
};

const VS_DXIL: &[u8] = include_bytes!("../shaders/vertex.dxil");
const PS_DXIL: &[u8] = include_bytes!("../shaders/pixel.dxil");

unsafe fn validate(dxil: &[u8]) -> Result<dxc::IDxcBlob> {
	let library: dxc::IDxcUtils = dxc::DxcCreateInstance(&dxc::CLSID_DxcLibrary)?;
	let validator: dxc::IDxcValidator = dxc::DxcCreateInstance(&dxc::CLSID_DxcValidator)?;
	let encoding: dxc::IDxcBlobEncoding =
		library.CreateBlob(dxil.as_ptr().cast(), dxil.len() as u32, dxc::DXC_CP(0))?;

	let validate: dxc::IDxcOperationResult =
		validator.Validate(&encoding, dxc::DxcValidatorFlags_InPlaceEdit)?;

	println!("{:?}", validate.GetResult());

	Ok(encoding.cast()?)
}

fn main() {
	unsafe {
		validate(VS_DXIL).expect("failed to validate vertex shader");
		validate(PS_DXIL).expect("failed to validate pixel shader");
	};
}
```
