### ISSUE TITLE
Version 58 and 59 breaks rust analyzer

### ISSUE THREAD

**Issue by numonce** [microsoft/windows-rs#3440]
### Summary

Crate versions 58 and 59 seemingly break rust analyzer on linux. Programs still build when cross compiling with the windows-gnu toolchain, but errors are thrown when executing the `cargo check` command. The below code throws errors with versions 58+ but not on previous versions. 

### Crate manifest

```TOML
[package]
name = "tester"
version = "0.1.0"
edition = "2021"

[dependencies]
windows = { version = "0.59.0", features = [
  "Win32_Foundation",
  "Win32",
  "Win32_System_Memory",
] }
```

### Crate code

```Rust
use windows::Win32;
fn main() {
    println!("Hello, world!");
}
```
