### ISSUE TITLE
Cannot use implement macro

### ISSUE THREAD

**Issue by alexiokay** [microsoft/windows-rs#3568]
### Summary

I'm tryiong to use implement macro from windows crate, but i get this error:

```
#[implement(IAudioEndpointVolumeCallback)]
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ could not find `windows_core` in the list of imported crates
```

### Crate manifest

```TOML
[package]
name = "VortiDeck"
default-run = "VortiDeck" 
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
license = ""
repository = ""
edition = "2024"
rust-version = "1.86.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "vortideck"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.0.5", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
log = "0.4"
tauri = { version = "2.2.5", features = ["tray-icon"] }
tauri-plugin-log = { version = "2.2.1", features = ["colored"] }
tauri-plugin-websocket = "2.3.0"

# certs = { path = "../certs"  }
pingora-reverse-proxy = { path = "../pingora-proxy-src",  features = ["proxy"]  }

tokio = { version = "1.42.0", features = ["full"] }
tokio-tungstenite = {version = "0.26.1", features = ["rustls", "native-tls"] }
tokio-rustls = "0.26.1"
rustls = "0.23.21"
rustls-pki-types = "1.10.1"
argh = "0.1.13"
rustls-pemfile = "2.2.0"
miette = {version="7.4.0", features= ["fancy"] }

thiserror = "2.0.5"
futures-channel = "0.3.31"
futures-util = "0.3.31"
tauri-plugin-shell = "2"
tracing-journald = "=0.3.1"
local-ip-address = "0.6.3"
simple-dns = "0.10.0"
mdns-sd = "0.13.1"
env_logger = "0.11.5"
qrcode = { version = "0.14.1", default-features = true }
image = "0.25.5"
base64 = "0.22.1"
platform-info = "2.0.4"
device_query = "3.0.0"
enigo = "0.3.0"
diesel = { version = "2.2.0", features = ["sqlite", "r2d2", "returning_clauses_for_sqlite_3_35"] }
diesel_migrations = "2.2.0"
dotenvy = "0.15"
tauri-plugin-store = "2"
dirs = "6.0.0"
tauri-plugin-fs = "2.2.0"
warp = "0.3.7"
diesel-derive-enum = { version = "2.1.0", features = ["sqlite"] }
tauri-plugin-process = "2"
tauri-plugin-deep-link = "2.0.0"
tauri-plugin-http = "2.3.0"
tauri-plugin-pinia = "3"
tauri-plugin-os = "2.2.1"
keyring = { version = "3.6.1", features = ["apple-native", "windows-native", "sync-secret-service"] }
reqwest = { version = "0.12.12", features = ["json", "cookies"] }
libsqlite3-sys = { version = "0.32.0", features = ["bundled"] }
pyo3 = { version = "0.24.1", features= ["auto-initialize", "abi3-py39", "generate-import-lib"] }

# MCP SERVER DEPS
rmcp = { version = "0.1", features = ["server", "transport-sse-server", "transport-io"] }

[target.'cfg(windows)'.dependencies]
winreg = "0.55.0"
windows = { version = "0.61.1", features = [
            "Win32_Foundation",
            "Win32_Media_Audio",
            "Win32_System_Com",
            "Win32_Media_Audio_Endpoints",
            "Win32_System_Com_StructuredStorage",
            "Win32_System_Variant",
            "Win32_System_Memory",
            "Win32_System_Power",
            "Win32_System_Registry"  ] }
#windows-implement = "0.60.0"


[dependencies.uuid]
version = "1.11.0"
features = [
    "v4",                # Lets you generate random UUIDs
    "fast-rng",          # Use a faster (but still sufficiently random) RNG
    "macro-diagnostics", # Enable better diagnostics for compile-time UUIDs
]

[target.'cfg(not(any(target_os = "android", target_os = "ios")))'.dependencies]
tauri-plugin-autostart = "2"
tauri-plugin-single-instance = {version = "2.2.3", features = ["deep-link"] }
tauri-plugin-updater = "2"

[target.'cfg(any(target_os = "macos", windows, target_os = "linux"))'.dependencies]
tauri-plugin-autostart = "2"

[[bin]]
name = "VortiDeck"
path = "src/main.rs"  # This is the main entry point for your Tauri app



#[target.'cfg(not(any(target_os = "android", target_arch = "wasm32")))'.dependencies.libsqlite3-sys]
#features = ["bundled"]
#version = "0.28"
```

### Crate code

```Rust

```
