### ISSUE TITLE
RegisterControlChangeNotify doesn't work

### ISSUE THREAD

**Issue by alexiokay** [microsoft/windows-rs#3571]
### Summary

I'm trying to implement notifications when system volume change, unfortunately the onNotify function doesnt fire..  RegisterControlChangeNotify is succesfully called.

registering callback:
```
 pub async fn register_volume_change_callback(app_handle: AppHandle) -> std::result::Result<(), Box<dyn std::error::Error>> {
      
        let (endpoint_volume, device_id_str) = Self::get_audio_endpoint_volume()?;

        let callback = VolumeCallback { app_handle: app_handle.clone() };
        // Create the callback directly without going through IUnknown
        let callback_object: IAudioEndpointVolumeCallback = callback.into();
        
        unsafe {
            endpoint_volume.RegisterControlChangeNotify(&callback_object)?;
        }
        
        Ok(())
    }
```

defining callback
```
#[cfg(target_os = "windows")]
#[implement(IAudioEndpointVolumeCallback)]
struct VolumeCallback {
    app_handle: AppHandle,
}

#[cfg(target_os = "windows")]
impl IAudioEndpointVolumeCallback_Impl for VolumeCallback_Impl {
    fn OnNotify(&self, pnotify: *mut AUDIO_VOLUME_NOTIFICATION_DATA) -> windows_core::Result<()> {
        println!("OnNotify called!"); // Debug log
        unsafe {
            if !pnotify.is_null() {
                let data = &*pnotify;
                let volume = data.fMasterVolume * 100.0;
                let muted = data.bMuted.as_bool();

              

                // Log the volume change
                println!("Volume changed (callback): {:.1}%, Muted: {}, Button: {:?}, IsButtonChange: {}", 
                    volume, muted, button_id, is_button_change);

             
            } else {
                println!("Received null notification data!"); // Debug log
            }
            Ok(())
        }
    }
}
```

### Crate manifest

```TOML
[package]
name = "VortiDeck"
default-run = "VortiDeck" 
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
license = ""
repository = ""
edition = "2024"
rust-version = "1.86.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.0.5", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
log = "0.4"
tauri = { version = "2.2.5", features = ["tray-icon"] }
tauri-plugin-log = { version = "2.2.1", features = ["colored"] }
tauri-plugin-websocket = "2.3.0"

# certs = { path = "../certs"  }
pingora-reverse-proxy = { path = "../pingora-proxy-src",  features = ["proxy"]  }

tokio = { version = "1.42.0", features = ["full"] }
tokio-tungstenite = {version = "0.26.1", features = ["rustls", "native-tls"] }
tokio-rustls = "0.26.1"
rustls = "0.23.21"
rustls-pki-types = "1.10.1"
argh = "0.1.13"
rustls-pemfile = "2.2.0"
miette = {version="7.4.0", features= ["fancy"] }

thiserror = "2.0.5"
futures-channel = "0.3.31"
futures-util = "0.3.31"
tauri-plugin-shell = "2"
tracing-journald = "=0.3.1"
local-ip-address = "0.6.3"
simple-dns = "0.10.0"
mdns-sd = "0.13.1"
env_logger = "0.11.5"
qrcode = { version = "0.14.1", default-features = true }
image = "0.25.5"
base64 = "0.22.1"
platform-info = "2.0.4"
device_query = "3.0.1"
enigo = "0.3.0"
diesel = { version = "2.2.0", features = ["sqlite", "r2d2", "returning_clauses_for_sqlite_3_35"] }
diesel_migrations = "2.2.0"
dotenvy = "0.15"
tauri-plugin-store = "2"
dirs = "6.0.0"
tauri-plugin-fs = "2.2.0"
warp = "0.3.7"
diesel-derive-enum = { version = "2.1.0", features = ["sqlite"] }
tauri-plugin-process = "2"
tauri-plugin-deep-link = "2.0.0"
tauri-plugin-http = "2.3.0"
tauri-plugin-pinia = "3"
tauri-plugin-os = "2.2.1"
keyring = { version = "3.6.1", features = ["apple-native", "windows-native", "sync-secret-service"] }
reqwest = { version = "0.12.12", features = ["json", "cookies"] }
libsqlite3-sys = { version = "0.32.0", features = ["bundled"] }
pyo3 = { version = "0.24.1", features= ["auto-initialize", "abi3-py39", "generate-import-lib"] }

# MCP SERVER DEPS
#rmcp = { version = "0.1", features = ["server", "transport-sse-server", "transport-io"] }
rmcp = { git = "https://github.com/modelcontextprotocol/rust-sdk", branch = "main", features=  ["client", "transport-child-process", "tower", "server", "transport-sse-server", "transport-io"] }

tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
rand = "0.9.0"
anyhow = "1.0"

tower = "0.5"

[target.'cfg(windows)'.dependencies]
winreg = "0.55.0"
windows = { version = "0.61.0", features = [
            "Win32_Foundation",
            "Win32_Media_Audio",
            "Win32_System_Com",
            "Win32_Media_Audio_Endpoints",
            "Win32_System_Com_StructuredStorage",
            "Win32_System_Variant",
            "Win32_System_Memory",
            "Win32_System_Power",
            "Win32_System_Registry"  ] }

windows-core = "0.61.0"
#windows-implement = "0.60.1"


[dependencies.uuid]
version = "1.11.0"
features = [
    "v4",                # Lets you generate random UUIDs
    "fast-rng",          # Use a faster (but still sufficiently random) RNG
    "macro-diagnostics", # Enable better diagnostics for compile-time UUIDs
]

[target.'cfg(not(any(target_os = "android", target_os = "ios")))'.dependencies]
tauri-plugin-autostart = "2"
tauri-plugin-single-instance = {version = "2.2.3", features = ["deep-link"] }
tauri-plugin-updater = "2"

[target.'cfg(any(target_os = "macos", windows, target_os = "linux"))'.dependencies]
tauri-plugin-autostart = "2"

[[bin]]
name = "VortiDeck"
path = "src/main.rs"  # This is the main entry point for your Tauri app



#[target.'cfg(not(any(target_os = "android", target_arch = "wasm32")))'.dependencies.libsqlite3-sys]
#features = ["bundled"]
#version = "0.28"
```

### Crate code

```Rust

```
