### ISSUE TITLE
DirectDraw functions have meaningless parameter names

### ISSUE THREAD

**Issue by ljbade** [microsoft/windows-rs#3592]
### Summary

For some reason the legacy DirectDraw interface functions have had their function parameter names changed to meaningless names.

For example, in Rust the `IDirectDraw::SetCooperativeLevel()` function has the following definition:
`pub unsafe fn SetCooperativeLevel(&self, param0: super::super::Foundation::HWND, param1: u32) -> windows_core::Result<()>`

In the DirectX SDK the function definition is:
`HRESULT SetCooperativeLevel(HWND hWnd, DWORD dwFlags)`

The Rust parameters are called `param0` and `param1` instead of `hWnd` and `dwFlags`.

### Crate manifest

```TOML
[package]
name = "gfx"
version = "0.1.0"
edition = "2024"

[dependencies]

[dependencies.windows]
version = "0.61"
features = [
    "Win32_Graphics_DirectDraw",
    "Win32_Graphics_Gdi",
    "Win32_System_Environment",
    "Win32_System_LibraryLoader",
    "Win32_System_Threading",
    "Win32_UI_WindowsAndMessaging",
]

```

### Crate code

```Rust

```
