### ISSUE TITLE
Win32 KillTimer returns Result instead of BOOL

### ISSUE THREAD

**Issue by ljbade** [microsoft/windows-rs#3596]
### Summary

The Rust binding for the Win32 [`KillTimer()`](https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-killtimer) function returns a `windows_core::Result<()>` instead of a `windows_core::BOOL`.

The definition on the Microsoft website lists it as returning a BOOL, with non-zero success and zero failure return values.

Since the binding returns a `Result`, when the call succeeds it returns a `Err(Error { code: HRESULT(0x00000000), message: "The operation completed successfully." })` value.

If you then try to use `unwrap()` on the result you get a panic:
```
thread 'main' panicked at src\window.rs:164:81:
called `Result::unwrap()` on an `Err` value: Error { code: HRESULT(0x00000000), message: "The operation completed successfully." }
```

### Crate manifest

```TOML
[package]
name = "kill_timer"
version = "0.1.0"
edition = "2024"

[dependencies]

[dependencies.windows]
version = "0.61"
features = ["Win32_UI_WindowsAndMessaging"]
```

### Crate code

```Rust
use windows::Win32::{
    Foundation::{GetLastError, HWND},
    UI::WindowsAndMessaging::{KillTimer, SetTimer},
};

const TIMER_ID: usize = 1;

unsafe extern "system" fn timer_proc(hwnd: HWND, _msg: u32, id_event: usize, _time: u32) {
    if hwnd.is_invalid() && id_event == TIMER_ID {
        println!("Timer tick!");
    }
}

fn main() {
    unsafe {
        if SetTimer(None, TIMER_ID, 0, Some(timer_proc)) == 0 {
            GetLastError().to_hresult().unwrap();
        }

        KillTimer(None, TIMER_ID).unwrap(); // unwrap() panics even though function call was successful
    }
}
```
