### ISSUE TITLE
Some COM API is incorrectly linked

### ISSUE THREAD

**Issue by edvard-pettersen-elas-ai** [microsoft/windows-rs#3618]
### Summary

Some COM API is incorrectly linking towards `ole32` when it should be linking against `onecore`. This results in `STATUS_ENTRYPOINT_NOT_FOUND` being thrown at runtime.

![Image](https://github.com/user-attachments/assets/a4763a6d-dad5-4813-aa73-b079a45ca04c)

I have found the following COM API to be incorrectly linked, but there may be more:
* `CoRegisterDeviceCatalog`
* `CoRevokeDeviceCatalog`

I am running 24H2 Build 26100.4202.

I can confirm that if I make my own bindings linking `onecore` then no exception is thrown.

### Crate manifest

```TOML
[package]
name = "repro"
version = "0.1.0"
edition = "2024"

[dependencies]
windows = { version = "0.61.1", features = ["Win32_System_Com"] }
```

### Crate code

```Rust
use windows::Win32::System::Com::*;
fn main() {
    let _ = unsafe { CoRegisterDeviceCatalog(None) };
}
```

**Comment by edvard-pettersen-elas-ai** [comment]
I see this is most likely a duplicate of https://github.com/microsoft/win32metadata/issues/1928, any progress on getting this fixed?

**Comment by kennykerr** [comment]
You may want to take it up on that issue you found. In Rust, you can workaround this by using the [windows-link](https://crates.io/crates/windows-link) crate directly. For example:

```toml
[dependencies]
windows-link = "0.1"
windows-strings = "0.4"
windows-result = "0.3"
```

```rust
use windows_link::link;
use windows_result::HRESULT;
use windows_strings::*;

link!("api-ms-win-core-com-l1-1-3.dll" "system" fn CoRegisterDeviceCatalog(id: PCWSTR, cookie: *mut *mut std::ffi::c_void) -> HRESULT);

fn main() {
    unsafe {
        let mut cookie = std::ptr::null_mut();
        CoRegisterDeviceCatalog(w!("device-id"), &mut cookie).unwrap();
    }
}
```
