### ISSUE TITLE
Support architecture-specific builds

### ISSUE THREAD

**Issue by ZCWorks** [microsoft/windows-rs#858]
in ver.0.11.0: Windows::Win32::UI::Shell::NOTIFYICONDATAW is "#[repr(C, packed(1))]" so Shell_NotifyIconW fails

in ver.0.10.0: it is "#[repr(C)]", Shell_NotifyIconW goes OK

**Comment by tim-weis** [comment]
The issue can be reproduced using the following:

Cargo.toml:
```toml
[package]
name = "shell_test"
version = "0.0.0"
edition = "2018"

[dependencies]
windows = "0.11.0"

[build-dependencies]
windows = "0.11.0"
```

build.rs:
```rust
fn main() {
    windows::build!(
        Windows::Win32::UI::Shell::NOTIFYICONDATAW,
    );
}
```

main.rs:
```rust
mod bindings {
    windows::include_bindings!();
}

fn main() {}
```

* `cargo build --target i686-pc-windows-msvc` produces the 32-bit bindings
* `cargo build --target x86_64-pc-windows-msvc` produces the 64-bit bindings

According to the Windows SDK headers, the `NOTIFIYICONDATAW` structure should be `packed(1)`, unless the target architecture is `_WIN64` (not sure whether that includes ARM64).

The metadata contains type definitions for both byte-packed and natural type layout, presumably gated on the `SupportedArchitecture` attribute (which ILSpy won't display, though [it should](https://github.com/microsoft/win32metadata/issues/472)).
